hw02_fix_app
AndrewSorokin540/home_work_basic pull request #1
Opened 2024-05-22 05:42 UTC by AndrewSorokin540

есть ошибки
main.go:4:2: "./printer" is relative, but relative import paths are not supported in module mode
main.go:5:2: "./reader" is relative, but relative import paths are not supported in module mode
main.go:6:2: "./types" is relative, but relative import paths are not supported in module mode

2024-05-22 05:50 UTC, vladislavmass requested changes

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/go.mod
Неверное имя модуля

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/main.go
> +	"./printer"
Пути импорта в go начинаются с  имени модуля. Поэтому изначальный вариант был более близок к верному, просто эти пути надо будет поправить после того, как будет исправлено имя модуля в go.mod

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/go.mod
Верное имя модуля это путь к его репозитарию+ путь к модулю внутри репозитария

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Ошибки нужно возвращать. Нет никакого смысла читать не существующий файл. `return nil,err`

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Ошибки нужно возвращать. Вызывающий код должен знать что пошло не так. `return nil,err`

2024-05-22 05:50 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Такое же замечание к строке кода  23

2024-05-22 07:22 UTC, AndrewSorokin540 commented on hw02_fix_app/main.go
> +	"./printer"
![image](https://github.com/AndrewSorokin540/home_work_basic/assets/55226383/68c677a2-b18f-4138-8c52-b4b240427c40)
теперь приложение работает, но IDE все подсвечивает красным. Что не так?

2024-05-22 08:08 UTC, AndrewSorokin540 commented on hw02_fix_app/main.go
> +	"./printer"
я включил го модули в ИДЕ - теперь все ок)

2024-05-22 08:14 UTC, vladislavmass commented on hw02_fix_app/main.go
> +	"./printer"
Отлично. Но хочу еще раз напомнить что для приема дз, оно должно проходить пайплайн. Который для данного репозитария не подключен

2024-05-22 10:16 UTC, vladislavmass requested changes

2024-05-22 10:16 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Эта проблема осталась

2024-05-22 10:16 UTC, vladislavmass commented on hw02_fix_app/types/employee.go
>  }
Будут проблемы в с парсингом полей в 6 и 9 строке. Так как в json у этих полей другие имена

2024-05-23 15:42 UTC, vladislavmass requested changes

2024-05-23 15:42 UTC, vladislavmass commented on hw02_fix_app/main.go
> +	var path = "data.json"
Нужно заменить `var path =` на `path:=`

2024-05-23 15:42 UTC, vladislavmass commented on hw02_fix_app/printer/pkg.go
>  		fmt.Println(str)
Уберите строку выше, оставьте только `fmt.Println(staff[i])`

2024-05-23 15:42 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  	res := data
Эта строка не несете никакой нагрузке можно сразу вернуть data

2024-05-24 05:40 UTC, vladislavmass approved these changes
Отличная работа

2024-05-27 08:14 UTC, merged